import { ROLES } from './roles'

export const PERMISSIONS = {
  VIEW_ALL_EMPLOYEES:   [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  MANAGE_EMPLOYEES:     [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  RUN_PAYROLL:          [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  VIEW_PAYROLL:         [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  MANAGE_ROLES:         [ROLES.SUPER_ADMIN],
  SYSTEM_SETTINGS:      [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  APPROVE_LEAVE:        [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  VIEW_REPORTS:         [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  MANAGE_RECRUITMENT:   [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.HR],
  VIEW_OWN_DATA:        [ROLES.EMPLOYEE, ROLES.MANAGER, ROLES.HR, ROLES.ADMIN, ROLES.SUPER_ADMIN],
}

export const hasPermission = (userRole, permission) =>
  PERMISSIONS[permission]?.includes(userRole) ?? false
